apiVersion: v1
kind: Service
metadata:
  name: {{ include "junction.fullname" . }}-api
  labels:
    {{- include "junction.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "junction.selectorLabels" (dict "context" . "component" "api") | nindent 4 }}
