apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "junction.fullname" . }}-nginx
  labels:
    {{- include "junction.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen {{ .Values.api.nginx.port }};

        location / {
            fastcgi_pass 127.0.0.1:{{ .Values.api.fpm.port }};
            fastcgi_index index.php;
            # app content lands under /env in the container, not /
            fastcgi_param SCRIPT_FILENAME /env/app/www/index.php;
            include fastcgi_params;
        }
    }
