apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "junction.fullname" . }}-system-worker
  labels:
    {{- include "junction.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.systemWorker.replicaCount }}
  selector:
    matchLabels:
      {{- include "junction.selectorLabels" (dict "context" . "component" "system-worker") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "junction.labels" . | nindent 8 }}
        {{- include "junction.selectorLabels" (dict "context" . "component" "system-worker") | nindent 8 }}
    spec:
      containers:
        - name: worker
          image: "{{ .Values.systemWorker.image.repository }}:{{ .Values.systemWorker.image.tag }}"
          imagePullPolicy: {{ .Values.systemWorker.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "junction.workerSecretName" . }}
          env:
            - name: JUNCTION_API_URL
              value: "http://{{ include "junction.fullname" . }}-api.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.api.service.port }}"
          resources:
            {{- toYaml .Values.systemWorker.resources | nindent 12 }}
